### ISSUE TITLE
Any documented test results?

### ISSUE THREAD

**Issue by SjoerdTimovanVliet** [eugeneALU/CECNL_RealTimeBCI#1]
Dear Eugene,

Do you maybe have any test results or videos confirming that the system has worked?  I need to verify if this github repository actually worked for my thesis. 
Thank you.

Best regards, 

Sjoerd

**Comment by eugeneALU** [comment]
Hi, 

It has been a long time since I built this repo. It does work back then but I cannot find the videos. 
The problem with this solution is the long reaction time, so cannot really control the drone smoothly.

This is all that I can provide now.

Best regards,

Eugene

**Comment by eugeneALU** [comment]
I've found and uploaded some demo videos. 

Best regards,

Eugene

**Comment by SjoerdTimovanVliet** [comment]
Hi Eugene,

Sincerely appreciated. Thank you

Best regards,

Sjoerd
